[workspace]
resolver = "3"
members = [
    "greem",
    "greem-build",
    "greem-macros",
    "greem-core",
    "greem-reference",
    "greem-compliance",
    "greem-test-app",
    "examples/axum",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
repository = "https://github.com/XiNiHa/greem"

[workspace.dependencies]
greem = { path = "greem", version = "0.0.1" }
greem-build = { path = "greem-build", version = "0.0.1" }
greem-macros = { path = "greem-macros", version = "0.0.1" }
greem-core = { path = "greem-core", version = "0.0.1" }
greem-reference = { path = "greem-reference" }
greem-test-app = { path = "greem-test-app" }
apollo-compiler = "1.33"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
self_cell = "1.2"
smallvec = { version = "1.13", features = ["union"] }
indexmap = "2"
