//! `Schema<I, C, Q, M>`: the runtime handle built once from the generated
//! schema module, with the request entry points.

use crate::context::Context;
use crate::error::{GraphQLError, InputError, SchemaError};
use crate::exec::complete::ObjectBatch;
use crate::exec::payload::{Payload, PayloadKind};
use crate::exec::pull::{Ship, pull};
use crate::exec::run::run_loop;
use crate::exec::scope::{Batch, ObjectMeta, ScopeMeta};
use crate::exec::state::{ExecuteOptions, GroupKind, Groups, IncrementalDelivery, Shared};
use crate::plan::{Leaf, PlanTable, Walker};
use crate::resolver::{NoMutation, Outputs};
use crate::tree::{Abort, Document, Tree, json_to_input, span_location};
use crate::value::InputValue;
use apollo_compiler::validation::Valid;
use apollo_compiler::{ExecutableDocument, Schema as ApolloSchema};
use futures::{Stream, StreamExt};
use std::marker::PhantomData;
use std::sync::{Arc, Mutex};

/// Generated per schema module: the embedded SDL and the root type tags.
pub trait SchemaInfo: Send + Sync + 'static {
    const SDL: &'static str;
    const BUILD_VERSION: &'static str;
    type Query;
    type Mutation;

    /// Runs the codec of the custom scalar `name` over an input value, so a
    /// variable is validated before execution; other names accept anything.
    fn check_scalar(_name: &str, _value: &InputValue) -> Result<(), InputError> {
        Ok(())
    }
}

/// The root values for one request.
pub struct Roots<Q, M = NoMutation> {
    pub query: Q,
    pub mutation: M,
}

impl<Q> Roots<Q, NoMutation> {
    pub fn query(query: Q) -> Self {
        Roots {
            query,
            mutation: NoMutation,
        }
    }
}

/// A handle to a built schema; clones share it.
pub struct Schema<I: SchemaInfo, C = (), Q = (), M = NoMutation> {
    inner: Arc<Inner>,
    _marker: Marker<I, C, Q, M>,
}

struct Inner {
    schema: Arc<Valid<ApolloSchema>>,
    implementers: apollo_compiler::collections::HashMap<
        apollo_compiler::Name,
        apollo_compiler::schema::Implementers,
    >,
    max_depth: u32,
    stream_capacity: usize,
    recursion_limit: Option<usize>,
    token_limit: Option<usize>,
}

impl<I: SchemaInfo, C, Q, M> Clone for Schema<I, C, Q, M> {
    fn clone(&self) -> Self {
        Schema {
            inner: self.inner.clone(),
            _marker: PhantomData,
        }
    }
}

type Marker<I, C, Q, M> = PhantomData<fn() -> (I, C, Q, M)>;

pub struct SchemaBuilder<I: SchemaInfo, C, Q, M> {
    max_depth: u32,
    stream_capacity: usize,
    recursion_limit: Option<usize>,
    token_limit: Option<usize>,
    _marker: Marker<I, C, Q, M>,
}

impl<I: SchemaInfo, C: Send + Sync + 'static> Schema<I, C, (), NoMutation> {
    pub fn builder() -> SchemaBuilder<I, C, (), NoMutation> {
        SchemaBuilder {
            max_depth: 32,
            stream_capacity: 100,
            recursion_limit: None,
            token_limit: None,
            _marker: PhantomData,
        }
    }
}

impl<I: SchemaInfo, C: Send + Sync + 'static, Q, M> SchemaBuilder<I, C, Q, M> {
    pub fn query<Q2: Outputs<I::Query, C>>(self) -> SchemaBuilder<I, C, Q2, M> {
        SchemaBuilder {
            max_depth: self.max_depth,
            stream_capacity: self.stream_capacity,
            recursion_limit: self.recursion_limit,
            token_limit: self.token_limit,
            _marker: PhantomData,
        }
    }

    pub fn mutation<M2: Outputs<I::Mutation, C>>(self) -> SchemaBuilder<I, C, Q, M2> {
        SchemaBuilder {
            max_depth: self.max_depth,
            stream_capacity: self.stream_capacity,
            recursion_limit: self.recursion_limit,
            token_limit: self.token_limit,
            _marker: PhantomData,
        }
    }

    /// The maximum execution depth (default 32); see the depth policy in the spec.
    pub fn max_depth(mut self, depth: u32) -> Self {
        self.max_depth = depth;
        self
    }

    /// Items buffered per stream turn (default 100).
    pub fn stream_capacity(mut self, capacity: usize) -> Self {
        self.stream_capacity = capacity.max(1);
        self
    }

    pub fn parser_recursion_limit(mut self, limit: usize) -> Self {
        self.recursion_limit = Some(limit);
        self
    }

    pub fn parser_token_limit(mut self, limit: usize) -> Self {
        self.token_limit = Some(limit);
        self
    }

    /// Both roots must be configured for what the schema declares: a
    /// declared `Mutation` without `.mutation::<M>()` does not compile.
    pub fn build(self) -> Result<Schema<I, C, Q, M>, SchemaError>
    where
        Q: Outputs<I::Query, C>,
        M: Outputs<I::Mutation, C>,
    {
        if I::BUILD_VERSION != crate::BUILD_VERSION {
            return Err(SchemaError(format!(
                "schema module was generated by greem-build {} but greem is {}; rebuild with matching versions",
                I::BUILD_VERSION,
                crate::BUILD_VERSION
            )));
        }
        let schema = ApolloSchema::parse_and_validate(I::SDL, "schema.graphql")
            .map_err(|e| SchemaError(e.to_string()))?;
        let implementers = schema.implementers_map();
        Ok(Schema {
            inner: Arc::new(Inner {
                schema: Arc::new(schema),
                implementers,
                max_depth: self.max_depth,
                stream_capacity: self.stream_capacity,
                recursion_limit: self.recursion_limit,
                token_limit: self.token_limit,
            }),
            _marker: PhantomData,
        })
    }
}

/// A request-level failure: parse, validation, variables or unknown operation.
#[derive(Debug, Clone)]
pub struct RequestErrors(pub Vec<GraphQLError>);

impl RequestErrors {
    pub fn into_payload(self) -> OwnedPayload {
        OwnedPayload::encode(Payload::request_error(self.0))
    }
}

/// One operation of a parsed document plus its variables.
pub struct Operation {
    pub document: Arc<Document>,
    pub operation_name: Option<String>,
    pub variables: serde_json::Value,
}

/// A serialized payload owned by the caller.
#[derive(Clone, Debug)]
pub struct OwnedPayload {
    pub kind: PayloadKind,
    pub has_next: Option<bool>,
    pub json: Vec<u8>,
}

impl OwnedPayload {
    /// The JSON encoder, for `Schema::execute_stream`.
    pub fn encode(payload: Payload<'_>) -> Self {
        OwnedPayload {
            kind: payload.kind(),
            has_next: payload.has_next(),
            json: serde_json::to_vec(&payload).expect("serialize payload"),
        }
    }

    pub fn as_str(&self) -> &str {
        std::str::from_utf8(&self.json).expect("payload JSON is UTF-8")
    }
}

/// Every payload of one execution, serialized.
#[derive(Clone, Debug, Default)]
pub struct ExecutionOutput {
    pub payloads: Vec<OwnedPayload>,
}

impl ExecutionOutput {
    pub fn is_incremental(&self) -> bool {
        self.payloads.first().is_some_and(|p| p.has_next.is_some())
    }

    /// The initial payload, or the request error. Every execution that runs
    /// to completion ships at least one payload.
    pub fn first(&self) -> &OwnedPayload {
        &self.payloads[0]
    }
}

impl<I: SchemaInfo, C: Send + Sync + 'static, Q, M> Schema<I, C, Q, M> {
    /// The schema this runtime serves: the merged SDL from greem-build, with
    /// any `@defer` and `@stream` definitions it supplied.
    pub fn sdl(&self) -> &'static str {
        I::SDL
    }

    pub fn max_depth(&self) -> u32 {
        self.inner.max_depth
    }

    /// Parses and validates a request document once; the result is shared
    /// between requests.
    pub fn parse(&self, source: &str) -> Result<Arc<Document>, RequestErrors> {
        let mut parser = apollo_compiler::parser::Parser::new();
        if let Some(limit) = self.inner.recursion_limit {
            parser = parser.recursion_limit(limit);
        }
        if let Some(limit) = self.inner.token_limit {
            parser = parser.token_limit(limit);
        }
        let doc = parser
            .parse_executable(&self.inner.schema, source, "request.graphql")
            .map_err(|e| RequestErrors(diagnostics_to_errors(&e.errors)))?;
        let doc = doc
            .validate(&self.inner.schema)
            .map_err(|e| RequestErrors(diagnostics_to_errors(&e.errors)))?;
        let overlaps = crate::tree::overlapping_streams(&doc, &self.inner.schema);
        if !overlaps.is_empty() {
            return Err(RequestErrors(overlaps));
        }
        Ok(Arc::new(Document { doc }))
    }

    fn prepare(&self, op: &Operation, options: ExecuteOptions) -> Result<Tree, RequestErrors> {
        let doc: &Valid<ExecutableDocument> = &op.document.doc;
        let operation = doc
            .operations
            .get(op.operation_name.as_deref())
            .map_err(|e| {
                RequestErrors(vec![GraphQLError::request(
                    e.message().to_string(),
                    Vec::new(),
                )])
            })?
            .clone();
        if operation.is_subscription() {
            return Err(RequestErrors(vec![GraphQLError::request(
                "subscriptions are not supported",
                Vec::new(),
            )]));
        }
        let variables: apollo_compiler::response::JsonMap = match &op.variables {
            serde_json::Value::Null => Default::default(),
            serde_json::Value::Object(map) => map
                .iter()
                .map(|(k, v)| {
                    (
                        apollo_compiler::response::serde_json_bytes::ByteString::from(k.as_str()),
                        apollo_compiler::response::JsonValue::from(v.clone()),
                    )
                })
                .collect(),
            _ => {
                return Err(RequestErrors(vec![GraphQLError::request(
                    "variables must be an object",
                    Vec::new(),
                )]));
            }
        };
        let coerced = apollo_compiler::request::coerce_variable_values(
            &self.inner.schema,
            &operation,
            &variables,
        )
        .map_err(|e| RequestErrors(vec![request_error_to_graphql(&e, &doc.sources)]))?;
        // apollo accepts any value for a custom scalar: its codec runs here,
        // so an invalid variable is a request error and nothing executes.
        for variable in &operation.variables {
            let Some(value) = coerced.get(variable.name.as_str()) else {
                continue;
            };
            check_scalars::<I>(&self.inner.schema, &variable.ty, value).map_err(|e| {
                RequestErrors(vec![GraphQLError::request(
                    format!("variable `${}` got an invalid value: {e}", variable.name),
                    span_location(variable.location(), doc),
                )])
            })?;
        }
        apollo_compiler::introspection::check_max_depth(doc, &operation)
            .map_err(|e| RequestErrors(vec![request_error_to_graphql(&e, &doc.sources)]))?;
        Ok(Tree::new(
            self.inner.schema.clone(),
            op.document.clone(),
            operation,
            coerced,
            options.incremental == IncrementalDelivery::Enabled,
            self.inner.max_depth,
        ))
    }

    fn introspection(&self, tree: &Tree) -> Result<Option<serde_json::Value>, RequestErrors> {
        let doc: &Valid<ExecutableDocument> = &tree.doc.doc;
        let has_introspection = tree
            .operation
            .root_fields(doc)
            .any(|f| matches!(f.name.as_str(), "__schema" | "__type"));
        if !has_introspection {
            return Ok(None);
        }
        let response = apollo_compiler::introspection::partial_execute(
            &self.inner.schema,
            &self.inner.implementers,
            doc,
            &tree.operation,
            &tree.variables,
        )
        .map_err(|e| RequestErrors(vec![request_error_to_graphql(&e, &doc.sources)]))?;
        let data = serde_json::to_value(response.data).unwrap_or(serde_json::Value::Null);
        Ok(Some(data))
    }

    /// Builds the execution tree and runs the planning pass over it. Returns
    /// the frozen Plan table, the introspection JSON and whether the
    /// operation is a mutation.
    fn plan(
        &self,
        op: &Operation,
        app: &C,
        options: ExecuteOptions,
    ) -> Result<(Arc<PlanTable>, Option<serde_json::Value>, bool), RequestErrors>
    where
        Q: Outputs<I::Query, C>,
        M: Outputs<I::Mutation, C>,
    {
        let mut tree = self.prepare(op, options)?;
        let introspection = self.introspection(&tree)?;
        let planning_ctx = Context::new(app, None);
        let mut table = PlanTable::default();
        let is_mutation = tree.is_mutation();
        let walk = {
            let mut walker = Walker::new(&mut tree, &mut table, &planning_ctx);
            if is_mutation {
                M::__walk(&mut walker, 0, &Leaf::default())
            } else {
                Q::__walk(&mut walker, 0, &Leaf::default())
            }
        };
        walk.map_err(|Abort(errors)| RequestErrors(errors))?;
        table.usages = tree.usages.clone();
        table.compute_beneath();
        Ok((Arc::new(table), introspection, is_mutation))
    }

    /// Prepares a request for the reference executor: the same planning as
    /// `execute_stream`, always non-incremental.
    #[doc(hidden)]
    #[cfg(feature = "reference-executor")]
    pub fn __prepare_reference(
        &self,
        op: &Operation,
        app: Arc<C>,
        options: ExecuteOptions,
    ) -> Result<(Arc<PlanTable>, Option<serde_json::Value>, bool), RequestErrors>
    where
        Q: Outputs<I::Query, C>,
        M: Outputs<I::Mutation, C>,
    {
        let options = ExecuteOptions {
            incremental: IncrementalDelivery::Disabled,
            ..options
        };
        self.plan(op, &app, options)
    }

    /// Plans and executes one request as a stream of payloads, each passed
    /// to `encode` while the executor's frames are alive; pass
    /// `OwnedPayload::encode` for owned JSON. Execution advances only while
    /// the stream is polled and pauses after each payload until the next
    /// poll. Dropping the stream cancels it, a mutation's root fields
    /// included.
    pub fn execute_stream<T, E>(
        &self,
        roots: Roots<Q, M>,
        ctx: C,
        op: Operation,
        options: ExecuteOptions,
        encode: E,
    ) -> impl Stream<Item = T> + Send + use<I, C, Q, M, T, E>
    where
        Q: Outputs<I::Query, C> + Send + Sync,
        M: Outputs<I::Mutation, C> + Send + Sync,
        T: Send,
        E: for<'p> FnMut(Payload<'p>) -> T + Send,
    {
        let schema = self.clone();
        pull(encode, move |mut outlet| async move {
            schema.run(roots, ctx, &op, options, &mut outlet).await
        })
    }

    /// The text path: parses and validates a whole request, then streams it
    /// like `execute_stream`.
    pub fn execute_request_stream<T, E>(
        &self,
        roots: Roots<Q, M>,
        ctx: C,
        request: crate::http::Request,
        options: ExecuteOptions,
        encode: E,
    ) -> impl Stream<Item = T> + Send + use<I, C, Q, M, T, E>
    where
        Q: Outputs<I::Query, C> + Send + Sync,
        M: Outputs<I::Mutation, C> + Send + Sync,
        T: Send,
        E: for<'p> FnMut(Payload<'p>) -> T + Send,
    {
        let schema = self.clone();
        pull(encode, move |mut outlet| async move {
            match schema.operation(request) {
                Ok(op) => schema.run(roots, ctx, &op, options, &mut outlet).await,
                Err(errors) => outlet.ship(Payload::request_error(errors.0)),
            }
        })
    }

    /// Executes and returns every payload as owned JSON.
    pub async fn execute(
        &self,
        roots: Roots<Q, M>,
        ctx: C,
        op: Operation,
        options: ExecuteOptions,
    ) -> ExecutionOutput
    where
        Q: Outputs<I::Query, C> + Send + Sync,
        M: Outputs<I::Mutation, C> + Send + Sync,
    {
        ExecutionOutput {
            payloads: self
                .execute_stream(roots, ctx, op, options, OwnedPayload::encode)
                .collect()
                .await,
        }
    }

    /// The text path, returning every payload as owned JSON.
    pub async fn execute_request(
        &self,
        roots: Roots<Q, M>,
        ctx: C,
        request: crate::http::Request,
        options: ExecuteOptions,
    ) -> ExecutionOutput
    where
        Q: Outputs<I::Query, C> + Send + Sync,
        M: Outputs<I::Mutation, C> + Send + Sync,
    {
        ExecutionOutput {
            payloads: self
                .execute_request_stream(roots, ctx, request, options, OwnedPayload::encode)
                .collect()
                .await,
        }
    }

    fn operation(&self, request: crate::http::Request) -> Result<Operation, RequestErrors> {
        let crate::http::Request {
            query,
            operation_name,
            variables,
            ..
        } = request;
        let Some(query) = query else {
            return Err(RequestErrors(vec![GraphQLError::request(
                "request has no query",
                Vec::new(),
            )]));
        };
        Ok(Operation {
            document: self.parse(&query)?,
            operation_name,
            variables: variables.unwrap_or(serde_json::Value::Null),
        })
    }

    async fn run(
        &self,
        roots: Roots<Q, M>,
        ctx: C,
        op: &Operation,
        options: ExecuteOptions,
        outlet: &mut dyn Ship,
    ) where
        Q: Outputs<I::Query, C> + Send + Sync,
        M: Outputs<I::Mutation, C> + Send + Sync,
    {
        let (table, introspection, is_mutation) = match self.plan(op, &ctx, options) {
            Ok(planned) => planned,
            Err(errors) => {
                outlet.ship(Payload::request_error(errors.0));
                return;
            }
        };
        let shared = Shared {
            groups: Mutex::new(Groups::new()),
            behavior: options.error_behavior,
            incremental: options.incremental == IncrementalDelivery::Enabled,
            capacity: self.inner.stream_capacity,
            table: table.clone(),
            introspection,
            has_streams: std::sync::atomic::AtomicBool::new(false),
            live_streams: std::sync::atomic::AtomicUsize::new(0),
            halted: std::sync::atomic::AtomicBool::new(false),
        };
        let Roots { query, mutation } = roots;
        // A failed root is marked once, at its own position, like any object.
        let failed = if is_mutation {
            mutation.__parent_error()
        } else {
            query.__parent_error()
        };
        if let Some(error) = failed {
            outlet.ship(Payload::failed_root(GraphQLError::from_error(
                error,
                Vec::new(),
                Vec::new(),
            )));
            return;
        }
        if is_mutation {
            let batch = root_batch::<M, I::Mutation, C>(mutation, &shared, &ctx, &table, true);
            let mut root = batch.start();
            run_loop(&mut root, &shared, outlet).await;
        } else {
            let batch = root_batch::<Q, I::Query, C>(query, &shared, &ctx, &table, false);
            let mut root = batch.start();
            run_loop(&mut root, &shared, outlet).await;
        }
    }
}

fn root_batch<'a, T, Ty, C>(
    value: T,
    shared: &'a Shared,
    app: &'a C,
    table: &'a PlanTable,
    serial: bool,
) -> ObjectBatch<'a, T, Ty, C>
where
    T: Outputs<Ty, C> + Send + Sync,
    C: Send + Sync,
{
    let entry = table.lookup(0, &Leaf::default()).expect("root plan entry");
    let header = table.header(entry);
    let mut pending = smallvec::SmallVec::new();
    let shared_sets;
    {
        let mut groups = shared.groups();
        for &usage in &header.introduced {
            let usage_def = &table.usages[usage as usize];
            let parent_group = match usage_def.parent {
                Some(p) => pending
                    .iter()
                    .find(|(u, _)| *u == p)
                    .map(|(_, g)| *g)
                    .unwrap_or(0),
                None => 0,
            };
            let g = groups.alloc(
                GroupKind::Defer {
                    usage,
                    label: usage_def.label.clone(),
                    path: std::sync::Arc::from([]),
                    after: None,
                },
                parent_group,
            );
            groups.set_carrier(g, std::sync::Arc::from(Vec::new()), 0);
            pending.push((usage, g));
        }
        groups.retain(0);
        for &(_, g) in &pending {
            groups.retain(g);
        }
        shared_sets = groups.alloc_shared(&header.sets, &pending, 0);
    }
    let contexts = (0..header.fields.len())
        .map(|i| {
            Context::new(
                app,
                Some(crate::context::HintAddr {
                    table,
                    entry,
                    field: i as u32,
                }),
            )
        })
        .collect();
    ObjectBatch {
        values: vec![value],
        contexts,
        path: std::sync::Arc::from(Vec::new()),
        signal: crate::exec::scope::Signal::root(),
        meta: ScopeMeta {
            entry,
            generation: 0,
            objects: vec![ObjectMeta {
                group: 0,
                parent: 0,
                indices: smallvec::SmallVec::new(),
                pending,
                shared: shared_sets,
            }],
            serial,
            parent: None,
        },
        shared,
        app,
        table,
        header,
        entry,
        keep: Default::default(),
        tag: PhantomData,
    }
}

/// Validates every custom scalar inside a coerced variable value of type `ty`.
fn check_scalars<I: SchemaInfo>(
    schema: &ApolloSchema,
    ty: &apollo_compiler::ast::Type,
    value: &apollo_compiler::response::JsonValue,
) -> Result<(), InputError> {
    use apollo_compiler::response::JsonValue;
    use apollo_compiler::schema::ExtendedType;
    if value.is_null() {
        return Ok(());
    }
    if ty.is_list() {
        let item = ty.item_type();
        return match value {
            JsonValue::Array(items) => items.iter().enumerate().try_for_each(|(i, value)| {
                check_scalars::<I>(schema, item, value).map_err(|e| e.at(&i.to_string()))
            }),
            single => check_scalars::<I>(schema, item, single),
        };
    }
    let name = ty.inner_named_type();
    match schema.types.get(name) {
        Some(ExtendedType::Scalar(scalar)) if !scalar.is_built_in() => {
            I::check_scalar(name.as_str(), &json_to_input(schema, Some(ty), value))
        }
        Some(ExtendedType::InputObject(object)) => match value {
            JsonValue::Object(fields) => {
                object.fields.iter().try_for_each(|(field, definition)| {
                    match fields.get(field.as_str()) {
                        Some(value) => check_scalars::<I>(schema, &definition.ty, value)
                            .map_err(|e| e.at(field.as_str())),
                        None => Ok(()),
                    }
                })
            }
            _ => Ok(()),
        },
        _ => Ok(()),
    }
}

fn diagnostics_to_errors(list: &apollo_compiler::validation::DiagnosticList) -> Vec<GraphQLError> {
    list.iter()
        .map(|d| {
            let locations = d
                .line_column_range()
                .map(|r| {
                    vec![crate::error::Location {
                        line: r.start.line,
                        column: r.start.column,
                    }]
                })
                .unwrap_or_default();
            GraphQLError::request(d.error.to_string(), locations)
        })
        .collect()
}

fn request_error_to_graphql(
    error: &apollo_compiler::request::RequestError,
    sources: &apollo_compiler::parser::SourceMap,
) -> GraphQLError {
    let locations = error
        .location()
        .and_then(|span| span.line_column(sources))
        .map(|lc| {
            vec![crate::error::Location {
                line: lc.line,
                column: lc.column,
            }]
        })
        .unwrap_or_default();
    GraphQLError::request(error.message().to_string(), locations)
}
