//! The code generator: one `TokenStream` per schema, formatted with
//! prettyplease. The shape it emits is the one `greem/tests/handwritten.rs`
//! writes by hand.

use crate::{Codec, DEFER_DIRECTIVE, Error, STREAM_DIRECTIVE};
use apollo_compiler::ast::Type;
use apollo_compiler::schema::{
    EnumType, ExtendedType, InputObjectType, InterfaceType, ObjectType, ScalarType, UnionType,
};
use apollo_compiler::validation::Valid;
use apollo_compiler::{Name, Schema};
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use std::collections::BTreeMap;

/// The shared GraphQL-name-to-identifier mapping (`greem-core`).
fn ident(name: &str) -> Ident {
    greem_core::ident(name, Span::call_site())
}

struct Gen<'s> {
    schema: &'s Valid<Schema>,
    scalars: &'s BTreeMap<String, Codec>,
    absent_aware: &'s [String],
    reference: bool,
    sdl: String,
}

pub(crate) fn generate(
    sources: &[(String, String)],
    scalars: &BTreeMap<String, Codec>,
    absent_aware: &[String],
    reference: bool,
) -> Result<String, Error> {
    let mut merged = String::new();
    for (_, text) in sources {
        merged.push_str(text);
        merged.push('\n');
    }
    let declared = declared_directives(&merged);
    let mut supplied = String::new();
    if !declared.iter().any(|d| d == "defer") {
        supplied.push_str(DEFER_DIRECTIVE);
    }
    if !declared.iter().any(|d| d == "stream") {
        supplied.push_str(STREAM_DIRECTIVE);
    }
    merged.push_str(&supplied);
    let mut builder = Schema::builder();
    for (path, text) in sources {
        builder = builder.parse(text.as_str(), path.as_str());
    }
    if !supplied.is_empty() {
        builder = builder.parse(supplied.as_str(), "greem-incremental-directives.graphql");
    }
    let schema = builder.build().map_err(|e| Error(e.to_string()))?;
    let schema = schema.validate().map_err(|e| Error(e.to_string()))?;
    let generator = Gen {
        schema: &schema,
        scalars,
        absent_aware,
        reference,
        sdl: merged,
    };
    let tokens = generator.module();
    let file: syn::File = syn::parse2(tokens.clone())
        .map_err(|e| Error(format!("generated code does not parse: {e}\n{tokens}")))?;
    Ok(format!(
        "// @generated by greem-build {}. Do not edit.\n{}",
        env!("CARGO_PKG_VERSION"),
        prettyplease::unparse(&file)
    ))
}

/// The directive names the SDL declares, from its parsed definitions (so
/// comments and look-alike names cannot fool the check).
fn declared_directives(sdl: &str) -> Vec<String> {
    let document = match apollo_compiler::ast::Document::parse(sdl, "schema.graphql") {
        Ok(document) => document,
        Err(errors) => errors.partial,
    };
    document
        .definitions
        .iter()
        .filter_map(|definition| match definition {
            apollo_compiler::ast::Definition::DirectiveDefinition(def) => {
                Some(def.name.to_string())
            }
            _ => None,
        })
        .collect()
}

impl Gen<'_> {
    /// Whether input object `from` reaches input object `target` through
    /// non-list positions, which would make the generated struct infinitely sized.
    fn reaches_directly(&self, from: &str, target: &str, visited: &mut Vec<String>) -> bool {
        let Some(ExtendedType::InputObject(input)) = self.schema.types.get(from) else {
            return false;
        };
        for field in input.fields.values() {
            let inner = match field.ty.as_ref() {
                Type::Named(n) | Type::NonNullNamed(n) => n.as_str(),
                _ => continue,
            };
            if inner == target {
                return true;
            }
            if !matches!(
                self.schema.types.get(inner),
                Some(ExtendedType::InputObject(_))
            ) || visited.iter().any(|v| v == inner)
            {
                continue;
            }
            visited.push(inner.to_owned());
            if self.reaches_directly(inner, target, visited) {
                return true;
            }
        }
        false
    }

    fn objects(&self) -> Vec<&ObjectType> {
        self.schema
            .types
            .values()
            .filter_map(|t| match t {
                ExtendedType::Object(o) if !o.is_built_in() => Some(o.as_ref()),
                _ => None,
            })
            .collect()
    }

    fn interfaces(&self) -> Vec<&InterfaceType> {
        self.schema
            .types
            .values()
            .filter_map(|t| match t {
                ExtendedType::Interface(i) => Some(i.as_ref()),
                _ => None,
            })
            .collect()
    }

    fn unions(&self) -> Vec<&UnionType> {
        self.schema
            .types
            .values()
            .filter_map(|t| match t {
                ExtendedType::Union(u) => Some(u.as_ref()),
                _ => None,
            })
            .collect()
    }

    fn enums(&self) -> Vec<&EnumType> {
        self.schema
            .types
            .values()
            .filter_map(|t| match t {
                ExtendedType::Enum(e) if !e.is_built_in() => Some(e.as_ref()),
                _ => None,
            })
            .collect()
    }

    fn input_objects(&self) -> Vec<&InputObjectType> {
        self.schema
            .types
            .values()
            .filter_map(|t| match t {
                ExtendedType::InputObject(i) => Some(i.as_ref()),
                _ => None,
            })
            .collect()
    }

    fn custom_scalars(&self) -> Vec<&ScalarType> {
        self.schema
            .types
            .values()
            .filter_map(|t| match t {
                ExtendedType::Scalar(s) if !s.is_built_in() => Some(s.as_ref()),
                _ => None,
            })
            .collect()
    }

    fn is_custom_scalar(&self, name: &str) -> bool {
        matches!(self.schema.types.get(name), Some(ExtendedType::Scalar(s)) if !s.is_built_in())
    }

    /// `super::` repeated `depth` times.
    fn root(depth: usize) -> TokenStream {
        let supers = std::iter::repeat_n(quote!(super::), depth);
        quote!(#(#supers)*)
    }

    fn tag_of(&self, name: &str, depth: usize) -> TokenStream {
        match name {
            "Int" => quote!(::greem::scalars::Int),
            "Float" => quote!(::greem::scalars::Float),
            "String" => quote!(::greem::scalars::String),
            "Boolean" => quote!(::greem::scalars::Boolean),
            "ID" => quote!(::greem::scalars::ID),
            _ => {
                let root = Self::root(depth);
                let id = ident(name);
                quote!(#root types::#id)
            }
        }
    }

    fn type_tag(&self, ty: &Type, depth: usize) -> TokenStream {
        match ty {
            Type::Named(n) => {
                let inner = self.tag_of(n, depth);
                quote!(::greem::Nullable<#inner>)
            }
            Type::NonNullNamed(n) => self.tag_of(n, depth),
            Type::List(inner) => {
                let inner = self.type_tag(inner, depth);
                quote!(::greem::Nullable<::greem::List<#inner>>)
            }
            Type::NonNullList(inner) => {
                let inner = self.type_tag(inner, depth);
                quote!(::greem::List<#inner>)
            }
        }
    }

    fn shape(ty: &Type) -> TokenStream {
        let mut levels = Vec::new();
        let mut cursor = ty;
        loop {
            match cursor {
                Type::List(inner) => {
                    levels.push(true);
                    cursor = inner;
                }
                Type::NonNullList(inner) => {
                    levels.push(false);
                    cursor = inner;
                }
                Type::Named(_) => return quote!(::greem::Shape::new(&[#(#levels),*], true)),
                Type::NonNullNamed(_) => return quote!(::greem::Shape::new(&[#(#levels),*], false)),
            }
        }
    }

    /// The Rust type of an input position (argument or input object field).
    fn input_type(&self, ty: &Type, depth: usize, maybe: bool) -> TokenStream {
        self.input_type_in(ty, depth, maybe, None)
    }

    /// The Rust type of an input position inside input object `enclosing`;
    /// a field that reaches its own type without a list in between is boxed.
    fn input_type_in(
        &self,
        ty: &Type,
        depth: usize,
        maybe: bool,
        enclosing: Option<&str>,
    ) -> TokenStream {
        let root = Self::root(depth);
        let named = |n: &Name| -> TokenStream {
            match n.as_str() {
                "Int" => quote!(::core::primitive::i32),
                "Float" => quote!(::core::primitive::f64),
                "String" | "ID" => quote!(::std::string::String),
                "Boolean" => quote!(::core::primitive::bool),
                other => {
                    let id = ident(other);
                    if self.is_custom_scalar(other) {
                        quote!(<#root types::#id as ::greem::Scalar>::Value)
                    } else if enclosing.is_some_and(|e| {
                        other == e || self.reaches_directly(other, e, &mut vec![other.to_owned()])
                    }) {
                        quote!(::std::boxed::Box<#root #id>)
                    } else {
                        quote!(#root #id)
                    }
                }
            }
        };
        match ty {
            Type::Named(n) => {
                let inner = named(n);
                if maybe {
                    quote!(::greem::Maybe<#inner>)
                } else {
                    quote!(::std::option::Option<#inner>)
                }
            }
            Type::NonNullNamed(n) => named(n),
            Type::List(inner) => {
                let inner = self.input_type(inner, depth, false);
                if maybe {
                    quote!(::greem::Maybe<::std::vec::Vec<#inner>>)
                } else {
                    quote!(::std::option::Option<::std::vec::Vec<#inner>>)
                }
            }
            Type::NonNullList(inner) => {
                let inner = self.input_type(inner, depth, false);
                quote!(::std::vec::Vec<#inner>)
            }
        }
    }

    /// A reader closure `|v: &InputValue| -> Result<T, InputError>` for a
    /// position that involves a custom scalar somewhere.
    fn reader(&self, ty: &Type, depth: usize, maybe: bool) -> TokenStream {
        let root = Self::root(depth);
        match ty {
            Type::Named(n) | Type::NonNullNamed(n) => {
                let id = ident(n);
                let inner = quote!(|v: &::greem::InputValue| ::greem::__private::scalar_from_input::<#root types::#id>(v));
                if matches!(ty, Type::NonNullNamed(_)) {
                    inner
                } else if maybe {
                    quote!(|v: &::greem::InputValue| match v {
                        ::greem::InputValue::Null => Ok(::greem::Maybe::Null),
                        other => (#inner)(other).map(::greem::Maybe::Value),
                    })
                } else {
                    quote!(|v: &::greem::InputValue| match v {
                        ::greem::InputValue::Null => Ok(None),
                        other => (#inner)(other).map(Some),
                    })
                }
            }
            Type::List(inner) | Type::NonNullList(inner) => {
                let item = self.reader(inner, depth, false);
                let list = quote!(|v: &::greem::InputValue| match v {
                    ::greem::InputValue::List(items) => items.iter().enumerate().map(|(i, item)| (#item)(item).map_err(|e| e.at(&i.to_string()))).collect::<::core::result::Result<::std::vec::Vec<_>, ::greem::InputError>>(),
                    ::greem::InputValue::Null => Err(::greem::InputError::new("expected a list, found null")),
                    other => (#item)(other).map(|x| vec![x]),
                });
                if matches!(ty, Type::NonNullList(_)) {
                    list
                } else if maybe {
                    quote!(|v: &::greem::InputValue| match v {
                        ::greem::InputValue::Null => Ok(::greem::Maybe::Null),
                        other => (#list)(other).map(::greem::Maybe::Value),
                    })
                } else {
                    quote!(|v: &::greem::InputValue| match v {
                        ::greem::InputValue::Null => Ok(None),
                        other => (#list)(other).map(Some),
                    })
                }
            }
        }
    }

    fn absent_expr(ty: &Type, maybe: bool) -> TokenStream {
        if ty.is_non_null() {
            quote!(|| Err(::greem::InputError::new("value is required")))
        } else if maybe {
            quote!(|| Ok(::greem::Maybe::Absent))
        } else {
            quote!(|| Ok(None))
        }
    }

    /// `field: <expr>?` initializer for one input position.
    fn field_reader(&self, name: &str, ty: &Type, depth: usize, maybe: bool) -> TokenStream {
        if self.is_custom_scalar(ty.inner_named_type()) {
            let present = self.reader(ty, depth, maybe);
            let absent = Self::absent_expr(ty, maybe);
            quote!(::greem::__private::read_field_with(v, #name, #present, #absent)?)
        } else {
            quote!(::greem::__private::read_field(v, #name)?)
        }
    }

    fn doc(description: &Option<apollo_compiler::Node<str>>) -> TokenStream {
        match description {
            Some(text) => {
                let text = text.as_ref();
                quote!(#[doc = #text])
            }
            None => quote!(),
        }
    }

    fn module(&self) -> TokenStream {
        let allow = quote!(#[allow(non_snake_case, non_camel_case_types, dead_code, unused_imports, unused_variables, clippy::all)]);
        let types = self.types_module();
        let field_modules: Vec<TokenStream> = self
            .objects()
            .iter()
            .map(|o| self.field_module(o))
            .collect();
        let enums: Vec<TokenStream> = self.enums().iter().map(|e| self.enum_item(e)).collect();
        let inputs: Vec<TokenStream> = self
            .input_objects()
            .iter()
            .map(|i| self.input_object_item(i))
            .collect();
        let private = self.private_module();
        quote! {
            #allow
            pub mod types { #types }
            #(#allow #field_modules)*
            #(#allow #enums)*
            #(#allow #inputs)*
            #allow
            #[doc(hidden)]
            pub mod __private { #private }
            #allow
            pub type Schema<C = (), Q = (), M = ::greem::NoMutation> = ::greem::Schema<__private::Info, C, Q, M>;
        }
    }

    fn types_module(&self) -> TokenStream {
        let mut items = Vec::new();
        for ty in self.schema.types.values() {
            let (name, description) = match ty {
                ExtendedType::Object(o) if !o.is_built_in() => (&o.name, &o.description),
                ExtendedType::Interface(i) => (&i.name, &i.description),
                ExtendedType::Union(u) => (&u.name, &u.description),
                ExtendedType::Enum(e) if !e.is_built_in() => (&e.name, &e.description),
                ExtendedType::Scalar(s) if !s.is_built_in() => (&s.name, &s.description),
                _ => continue,
            };
            let doc = Self::doc(description);
            let id = ident(name);
            items.push(quote!(#doc pub struct #id;));
        }
        quote!(#(#items)*)
    }

    fn field_module(&self, object: &ObjectType) -> TokenStream {
        let module = ident(&object.name);
        let doc = Self::doc(&object.description);
        let markers: Vec<TokenStream> = object
            .fields
            .values()
            .map(|field| {
                let marker = ident(&field.name);
                let name = field.name.as_str();
                let fdoc = Self::doc(&field.description);
                let ty = self.type_tag(&field.ty, 1);
                let shape = Self::shape(&field.ty);
                let args = if field.arguments.is_empty() {
                    quote!(())
                } else {
                    quote!(super::__private::args::#module::#marker)
                };
                quote! {
                    #fdoc
                    pub struct #marker;
                    impl ::greem::Field for #marker {
                        type Args = #args;
                        type Type = #ty;
                        const NAME: &'static ::core::primitive::str = #name;
                        const SHAPE: ::greem::Shape = #shape;
                    }
                }
            })
            .collect();
        quote! {
            #doc
            pub mod #module {
                #(#markers)*
            }
        }
    }

    fn enum_item(&self, e: &EnumType) -> TokenStream {
        let id = ident(&e.name);
        let name = e.name.as_str();
        let doc = Self::doc(&e.description);
        let variants: Vec<Ident> = e.values.keys().map(|v| ident(v)).collect();
        let names: Vec<&str> = e.values.keys().map(|v| v.as_str()).collect();
        let docs: Vec<TokenStream> = e
            .values
            .values()
            .map(|v| Self::doc(&v.description))
            .collect();
        quote! {
            #doc
            #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
            pub enum #id { #(#docs #variants),* }
            impl ::greem::Enum for #id {
                const VALUES: &'static [#id] = &[#(#id::#variants),*];
                fn name(self) -> &'static ::core::primitive::str {
                    match self { #(#id::#variants => #names),* }
                }
                fn from_name(name: &::core::primitive::str) -> ::core::option::Option<Self> {
                    match name { #(#names => ::core::option::Option::Some(#id::#variants),)* _ => ::core::option::Option::None }
                }
            }
            impl ::greem::FromInput for #id {
                fn from_input(value: &::greem::InputValue) -> ::core::result::Result<Self, ::greem::InputError> {
                    match value {
                        ::greem::InputValue::Enum(v) => <Self as ::greem::Enum>::from_name(v).ok_or_else(|| ::greem::InputError::new(format!("`{v}` is not a value of enum {}", #name))),
                        other => ::core::result::Result::Err(::greem::InputError::new(format!("expected enum {}, found {}", #name, other.kind()))),
                    }
                }
            }
            impl ::greem::__private::ToLeaf<types::#id> for #id {
                fn to_leaf<'a>(self) -> ::core::result::Result<::greem::Value<'a>, ::greem::Error> where Self: 'a {
                    ::core::result::Result::Ok(::greem::Value::Str(::std::borrow::Cow::Borrowed(<Self as ::greem::Enum>::name(self))))
                }
            }
            impl ::greem::__private::ToLeaf<types::#id> for &#id {
                fn to_leaf<'a>(self) -> ::core::result::Result<::greem::Value<'a>, ::greem::Error> where Self: 'a {
                    ::core::result::Result::Ok(::greem::Value::Str(::std::borrow::Cow::Borrowed(<#id as ::greem::Enum>::name(*self))))
                }
            }
        }
    }

    fn input_object_item(&self, input: &InputObjectType) -> TokenStream {
        let id = ident(&input.name);
        let doc = Self::doc(&input.description);
        let maybe = self.absent_aware.iter().any(|t| t == input.name.as_str());
        let fields: Vec<TokenStream> = input
            .fields
            .values()
            .map(|f| {
                let fid = ident(&f.name);
                let fdoc = Self::doc(&f.description);
                let use_maybe = maybe && !f.ty.is_non_null() && f.default_value.is_none();
                let ty = self.input_type_in(&f.ty, 0, use_maybe, Some(input.name.as_str()));
                quote!(#fdoc pub #fid: #ty,)
            })
            .collect();
        let readers: Vec<TokenStream> = input
            .fields
            .values()
            .map(|f| {
                let fid = ident(&f.name);
                let use_maybe = maybe && !f.ty.is_non_null() && f.default_value.is_none();
                let reader = self.field_reader(f.name.as_str(), &f.ty, 0, use_maybe);
                quote!(#fid: #reader,)
            })
            .collect();
        quote! {
            #doc
            #[derive(Clone, Debug)]
            pub struct #id { #(#fields)* }
            // The module-level `allow` reaches only the struct above.
            #[allow(clippy::all)]
            impl ::greem::FromInput for #id {
                fn from_input(v: &::greem::InputValue) -> ::core::result::Result<Self, ::greem::InputError> {
                    match v {
                        ::greem::InputValue::Object(_) => Ok(Self { #(#readers)* }),
                        other => Err(::greem::InputError::new(format!("expected input object, found {}", other.kind()))),
                    }
                }
            }
        }
    }

    fn private_module(&self) -> TokenStream {
        let sdl = &self.sdl;
        let args = self.args_module();
        let plans = self.plans_module();
        let objects: Vec<TokenStream> =
            self.objects().iter().map(|o| self.object_impl(o)).collect();
        let abstracts: Vec<TokenStream> = self
            .interfaces()
            .iter()
            .map(|i| self.abstract_impl(&i.name, &self.interface_members(i)))
            .chain(self.unions().iter().map(|u| {
                self.abstract_impl(
                    &u.name,
                    &u.members.iter().map(|m| m.name.clone()).collect::<Vec<_>>(),
                )
            }))
            .collect();
        let enums: Vec<TokenStream> = self
            .enums()
            .iter()
            .map(|e| {
                let tag = ident(&e.name);
                Self::leaf_completion(&tag, quote!(rt::ToLeaf<super::types::#tag>))
            })
            .collect();
        let scalars: Vec<TokenStream> = self
            .custom_scalars()
            .iter()
            .map(|s| self.scalar_items(s))
            .collect();
        let query = self
            .schema
            .root_operation(apollo_compiler::ast::OperationType::Query)
            .map(|n| ident(n));
        let query = match query {
            Some(q) => quote!(super::types::#q),
            None => quote!(::greem::NoMutationType),
        };
        let mutation = match self
            .schema
            .root_operation(apollo_compiler::ast::OperationType::Mutation)
        {
            Some(m) => {
                let m = ident(m);
                quote!(super::types::#m)
            }
            None => quote!(::greem::NoMutationType),
        };
        // The generator's own version, embedded as a literal: the runtime compares
        // it with its own at `build()`.
        let build_version = env!("CARGO_PKG_VERSION");
        let scalar_checks: Vec<TokenStream> = self
            .custom_scalars()
            .iter()
            .map(|scalar| {
                let name = scalar.name.as_str();
                let tag = ident(name);
                quote!(#name => rt::scalar_from_input::<super::types::#tag>(value).map(|_| ()),)
            })
            .collect();
        quote! {
            use ::greem::__private as rt;
            use ::greem::{Field, Outputs, Resolver};
            pub const SDL: &::core::primitive::str = #sdl;
            pub mod args { #args }
            pub mod plans { #plans }
            #(#objects)*
            #(#abstracts)*
            #(#enums)*
            #(#scalars)*
            pub struct Info;
            impl rt::SchemaInfo for Info {
                const SDL: &'static ::core::primitive::str = SDL;
                const BUILD_VERSION: &'static ::core::primitive::str = #build_version;
                type Query = #query;
                type Mutation = #mutation;
                fn check_scalar(name: &::core::primitive::str, value: &::greem::InputValue) -> ::core::result::Result<(), ::greem::InputError> {
                    match name {
                        #(#scalar_checks)*
                        _ => ::core::result::Result::Ok(()),
                    }
                }
            }
        }
    }

    fn interface_members(&self, interface: &InterfaceType) -> Vec<Name> {
        let mut members = Vec::new();
        for object in self.objects() {
            if object
                .implements_interfaces
                .contains(interface.name.as_str())
            {
                members.push(object.name.clone());
            }
        }
        for sub in self.interfaces() {
            if sub.implements_interfaces.contains(interface.name.as_str()) {
                members.push(sub.name.clone());
            }
        }
        members
    }

    fn args_module(&self) -> TokenStream {
        let mut modules = Vec::new();
        for object in self.objects() {
            let module = ident(&object.name);
            let mut items = Vec::new();
            for field in object.fields.values() {
                if field.arguments.is_empty() {
                    continue;
                }
                let id = ident(&field.name);
                let fields: Vec<TokenStream> = field
                    .arguments
                    .iter()
                    .map(|a| {
                        let aid = ident(&a.name);
                        let adoc = Self::doc(&a.description);
                        let ty = self.input_type(&a.ty, 3, false);
                        quote!(#adoc pub #aid: #ty,)
                    })
                    .collect();
                let readers: Vec<TokenStream> = field
                    .arguments
                    .iter()
                    .map(|a| {
                        let aid = ident(&a.name);
                        let reader = self.field_reader(a.name.as_str(), &a.ty, 3, false);
                        quote!(#aid: #reader,)
                    })
                    .collect();
                let doc = format!("Arguments of `{}.{}`.", object.name, field.name);
                items.push(quote! {
                    #[doc = #doc]
                    #[derive(Clone, Debug)]
                    pub struct #id { #(#fields)* }
                    impl ::greem::FromInput for #id {
                        fn from_input(v: &::greem::InputValue) -> ::core::result::Result<Self, ::greem::InputError> {
                            Ok(Self { #(#readers)* })
                        }
                        fn from_absent() -> ::core::result::Result<Self, ::greem::InputError> {
                            Self::from_input(&::greem::InputValue::Object(::std::vec::Vec::new()))
                        }
                    }
                });
            }
            if !items.is_empty() {
                modules.push(quote!(pub mod #module { #(#items)* }));
            }
        }
        quote!(#(#modules)*)
    }

    fn plans_module(&self) -> TokenStream {
        let items: Vec<TokenStream> = self
            .objects()
            .iter()
            .map(|object| {
                let module = ident(&object.name);
                let variants: Vec<TokenStream> = object
                    .fields
                    .values()
                    .map(|f| {
                        let marker = ident(&f.name);
                        quote!(#marker(rt::FieldArgs<super::super::super::#module::#marker>))
                    })
                    .collect();
                quote! {
                    pub mod #module {
                        use ::greem::__private as rt;
                        pub enum Field { #(#variants,)* __other }
                        pub struct Plan(pub ::std::vec::Vec<Field>);
                    }
                }
            })
            .collect();
        quote!(#(#items)*)
    }

    fn object_impl(&self, object: &ObjectType) -> TokenStream {
        let tag = ident(&object.name);
        let module = ident(&object.name);
        let name = object.name.as_str();
        let markers: Vec<Ident> = object.fields.values().map(|f| ident(&f.name)).collect();
        let names: Vec<&str> = object.fields.values().map(|f| f.name.as_str()).collect();
        let witness = markers
            .first()
            .expect("object types have at least one field")
            .clone();
        let reference = if self.reference {
            quote! {
                fn reference<'v, 's: 'v>(value: T, rc: &rt::RefCompletion<'s, C>) -> rt::futures::future::BoxFuture<'v, rt::RefValue>
                where T: 'v, C: 'v,
                {
                    if let Some(error) = <T as Resolver<super::#module::#witness, C>>::parent_error(&value) {
                        return rc.error(error.clone());
                    }
                    let rc = rc.clone();
                    Box::pin(async move {
                        let value = value;
                        rt::reference_object(&value, &rc, #name, |value, entry, i, rc| {
                            let plan: &plans::#module::Plan = rc.typed(entry);
                            match &plan.0[i as usize] {
                                #(plans::#module::Field::#markers(args) => rt::reference_field::<T, super::#module::#markers, C>(value, entry, i, args, rc),)*
                                plans::#module::Field::__other => Box::pin(async { Ok(rt::serde_json::Value::Null) }),
                            }
                        }).await
                    })
                }
            }
        } else {
            quote!()
        };
        quote! {
            impl rt::InnerKind for super::types::#tag { const OBJECTS: bool = true; }
            impl<T, C> rt::Completes<T, C> for super::types::#tag
            where
                T: #(Resolver<super::#module::#markers, C> +)* Send + Sync,
                C: Send + Sync + 'static,
            {
                const TYPENAME: &'static ::core::primitive::str = #name;

                fn walk<'a>(w: &mut rt::Walker<'_, C>, node: rt::NodeId, leaf: &rt::Leaf) -> Result<(), rt::Abort>
                where T: 'a, C: 'a,
                {
                    let entry = w.enter(node, leaf, #name)?;
                    let n = w.field_count(entry);
                    let mut fields = Vec::with_capacity(n);
                    for i in 0..n {
                        match w.field_name(entry, i) {
                            #(#names => {
                                let args = w.coerce::<super::#module::#markers>(entry, i);
                                if args.is_ok() { w.hints::<T, super::#module::#markers>(entry, i); }
                                fields.push(plans::#module::Field::#markers(args));
                            })*
                            _ => fields.push(plans::#module::Field::__other),
                        }
                    }
                    for i in 0..n {
                        match &fields[i] {
                            #(plans::#module::Field::#markers(Ok(args)) => {
                                w.descend(entry, i, |w, child, leaf| {
                                    <<T as Resolver<super::#module::#markers, C>>::Output<'a> as Outputs<<super::#module::#markers as Field>::Type, C>>::__walk(w, child, leaf)
                                })?;
                                w.plan::<T, super::#module::#markers>(entry, i, args);
                            })*
                            _ => {}
                        }
                    }
                    w.set_typed(entry, Box::new(plans::#module::Plan(fields)));
                    Ok(())
                }

                fn parent_error(value: &T) -> ::core::option::Option<&::greem::Error> {
                    <T as Resolver<super::#module::#witness, C>>::parent_error(value)
                }

                fn complete<'a>(values: Vec<T>, positions: Vec<rt::Pos>, cc: &mut rt::Completion<'a, '_, C>)
                where T: 'a, C: 'a,
                {
                    let mut ok = Vec::with_capacity(values.len());
                    let mut ok_pos = Vec::with_capacity(values.len());
                    for (value, pos) in values.into_iter().zip(positions) {
                        match <T as Resolver<super::#module::#witness, C>>::parent_error(&value) {
                            Some(error) => cc.error(&pos, error.clone()),
                            None => { ok.push(value); ok_pos.push(pos); }
                        }
                    }
                    cc.object_scope::<T, super::types::#tag>(ok, ok_pos);
                }

                fn start_fields<'a>(cx: &rt::FieldsCx<'a, C>, parents: &[&'a T], set: usize) -> Vec<rt::FieldFuture<'a>>
                where T: 'a, C: 'a,
                {
                    let plan: &'a plans::#module::Plan = cx.table.typed(cx.entry);
                    cx.header.sets[set].1.iter().map(|&i| match &plan.0[i as usize] {
                        #(plans::#module::Field::#markers(args) => rt::field::<T, super::#module::#markers, C>(cx, i, parents, args),)*
                        plans::#module::Field::__other => match cx.header.fields[i as usize].kind {
                            rt::FieldKind::Typename => rt::typename_field(cx, i),
                            _ => rt::introspection_field(cx, i),
                        },
                    }).collect()
                }

                #reference
            }
        }
    }

    fn abstract_impl(&self, name: &Name, members: &[Name]) -> TokenStream {
        let tag = ident(name);
        let arms: Vec<TokenStream> = members
            .iter()
            .enumerate()
            .map(|(step, member)| {
                let step = step as u8;
                let member = ident(member);
                quote! {
                    impl<T, C> rt::Completes<::greem::As<super::types::#member, T>, C> for super::types::#tag
                    where T: Outputs<super::types::#member, C> + Send, C: Send + Sync + 'static,
                    {
                        fn walk<'a>(w: &mut rt::Walker<'_, C>, node: rt::NodeId, leaf: &rt::Leaf) -> Result<(), rt::Abort>
                        where ::greem::As<super::types::#member, T>: 'a, C: 'a,
                        {
                            rt::walk_as::<super::types::#member, T, C>(#step, w, node, leaf)
                        }
                        fn first_error(value: &::greem::As<super::types::#member, T>, indices: &mut ::std::vec::Vec<u32>, wanted: &dyn Fn(&[u32]) -> bool) -> ::core::option::Option<::greem::Error> {
                            T::__first_error(&value.0, indices, wanted)
                        }

                        fn complete<'a>(values: Vec<::greem::As<super::types::#member, T>>, positions: Vec<rt::Pos>, cc: &mut rt::Completion<'a, '_, C>)
                        where ::greem::As<super::types::#member, T>: 'a, C: 'a,
                        {
                            rt::complete_as::<super::types::#member, T, C>(#step, values, positions, cc)
                        }
                        fn reference<'v, 's: 'v>(value: ::greem::As<super::types::#member, T>, rc: &rt::RefCompletion<'s, C>) -> rt::futures::future::BoxFuture<'v, rt::RefValue>
                        where ::greem::As<super::types::#member, T>: 'v, C: 'v,
                        {
                            T::__reference(value.into_inner(), &rc.with_leaf(#step))
                        }
                    }
                }
            })
            .collect();
        quote! {
            impl rt::InnerKind for super::types::#tag { const OBJECTS: bool = true; }
            #(#arms)*
            impl<A, B, C> rt::Completes<::greem::Either<A, B>, C> for super::types::#tag
            where super::types::#tag: rt::Completes<A, C> + rt::Completes<B, C>, A: Send, B: Send, C: Send + Sync + 'static,
            {
                fn walk<'a>(w: &mut rt::Walker<'_, C>, node: rt::NodeId, leaf: &rt::Leaf) -> Result<(), rt::Abort>
                where ::greem::Either<A, B>: 'a, C: 'a,
                {
                    rt::walk_either::<super::types::#tag, A, B, C>(w, node, leaf)
                }
                fn first_error(value: &::greem::Either<A, B>, indices: &mut ::std::vec::Vec<u32>, wanted: &dyn Fn(&[u32]) -> bool) -> ::core::option::Option<::greem::Error> {
                    match value {
                        ::greem::Either::A(a) => <super::types::#tag as rt::Completes<A, C>>::first_error(a, indices, wanted),
                        ::greem::Either::B(b) => <super::types::#tag as rt::Completes<B, C>>::first_error(b, indices, wanted),
                    }
                }

                fn complete<'a>(values: Vec<::greem::Either<A, B>>, positions: Vec<rt::Pos>, cc: &mut rt::Completion<'a, '_, C>)
                where ::greem::Either<A, B>: 'a, C: 'a,
                {
                    rt::complete_either::<super::types::#tag, A, B, C>(values, positions, cc)
                }
                fn reference<'v, 's: 'v>(value: ::greem::Either<A, B>, rc: &rt::RefCompletion<'s, C>) -> rt::futures::future::BoxFuture<'v, rt::RefValue>
                where ::greem::Either<A, B>: 'v, C: 'v,
                {
                    match value {
                        ::greem::Either::A(a) => <super::types::#tag as rt::Completes<A, C>>::reference(a, &rc.with_leaf(0)),
                        ::greem::Either::B(b) => <super::types::#tag as rt::Completes<B, C>>::reference(b, &rc.with_leaf(1)),
                    }
                }
            }
            impl<X, C> rt::Completes<Result<X, ::greem::Error>, C> for super::types::#tag
            where X: Outputs<super::types::#tag, C> + Send, C: Send + Sync + 'static,
            {
                fn walk<'a>(w: &mut rt::Walker<'_, C>, node: rt::NodeId, leaf: &rt::Leaf) -> Result<(), rt::Abort>
                where Result<X, ::greem::Error>: 'a, C: 'a,
                {
                    X::__walk(w, node, leaf)
                }
                fn first_error(value: &Result<X, ::greem::Error>, indices: &mut ::std::vec::Vec<u32>, wanted: &dyn Fn(&[u32]) -> bool) -> ::core::option::Option<::greem::Error> {
                    match value {
                        Ok(v) => X::__first_error(v, indices, wanted),
                        Err(e) => wanted(indices).then(|| e.clone()),
                    }
                }

                fn complete<'a>(values: Vec<Result<X, ::greem::Error>>, positions: Vec<rt::Pos>, cc: &mut rt::Completion<'a, '_, C>)
                where Result<X, ::greem::Error>: 'a, C: 'a,
                {
                    let mut ok = Vec::new();
                    let mut ok_pos = Vec::new();
                    for (value, pos) in values.into_iter().zip(positions) {
                        match value {
                            Ok(v) => { ok.push(v); ok_pos.push(pos); }
                            Err(e) => cc.error(&pos, e),
                        }
                    }
                    X::__complete(ok, ok_pos, cc)
                }
                fn reference<'v, 's: 'v>(value: Result<X, ::greem::Error>, rc: &rt::RefCompletion<'s, C>) -> rt::futures::future::BoxFuture<'v, rt::RefValue>
                where Result<X, ::greem::Error>: 'v, C: 'v,
                {
                    match value {
                        Ok(v) => X::__reference(v, rc),
                        Err(e) => rc.error(e),
                    }
                }
            }
        }
    }

    fn leaf_completion(tag: &Ident, bound: TokenStream) -> TokenStream {
        quote! {
            impl rt::InnerKind for super::types::#tag { const OBJECTS: bool = false; }
            impl<T, C> rt::Completes<T, C> for super::types::#tag
            where T: #bound + Send,
            {
                fn walk<'a>(_: &mut rt::Walker<'_, C>, _: rt::NodeId, _: &rt::Leaf) -> Result<(), rt::Abort>
                where T: 'a, C: 'a,
                {
                    Ok(())
                }
                fn first_error(value: &T, indices: &mut ::std::vec::Vec<u32>, wanted: &dyn Fn(&[u32]) -> bool) -> ::core::option::Option<::greem::Error> {
                    value
                        .leaf_error()
                        .or_else(|| value.leaf_is_null().then(rt::null_at_non_null))
                        .filter(|_| wanted(indices))
                }
                fn null_leaf(value: &T) -> bool {
                    value.leaf_is_null()
                }

                fn complete<'a>(values: Vec<T>, positions: Vec<rt::Pos>, cc: &mut rt::Completion<'a, '_, C>)
                where T: 'a, C: 'a,
                {
                    for (value, pos) in values.into_iter().zip(&positions) {
                        cc.leaf(pos, value.to_leaf());
                    }
                }
                fn reference<'v, 's: 'v>(value: T, rc: &rt::RefCompletion<'s, C>) -> rt::futures::future::BoxFuture<'v, rt::RefValue>
                where T: 'v, C: 'v,
                {
                    rc.leaf(value.to_leaf())
                }
            }
        }
    }

    fn scalar_items(&self, s: &ScalarType) -> TokenStream {
        let tag = ident(&s.name);
        let codec = match self.scalars.get(s.name.as_str()) {
            Some(Codec::Uuid) => quote! {
                impl ::greem::Scalar for super::types::#tag {
                    type Value = ::uuid::Uuid;
                    fn to_value(value: &Self::Value) -> ::greem::Value<'_> {
                        ::greem::Value::Str(::std::borrow::Cow::Owned(value.to_string()))
                    }
                    fn from_input(value: &::greem::InputValue) -> ::core::result::Result<Self::Value, ::greem::InputError> {
                        match value {
                            ::greem::InputValue::String(s) => s.parse().map_err(|e| ::greem::InputError::new(format!("invalid UUID: {e}"))),
                            other => Err(::greem::InputError::new(format!("expected a UUID string, found {}", other.kind()))),
                        }
                    }
                }
            },
            Some(Codec::Json) => quote! {
                impl ::greem::Scalar for super::types::#tag {
                    type Value = ::serde_json::Value;
                    fn to_value(value: &Self::Value) -> ::greem::Value<'_> {
                        ::greem::Value::from_json(value)
                    }
                    fn from_input(value: &::greem::InputValue) -> ::core::result::Result<Self::Value, ::greem::InputError> {
                        Ok(value.to_json())
                    }
                }
            },
            Some(Codec::String) => quote! {
                impl ::greem::Scalar for super::types::#tag {
                    type Value = ::std::string::String;
                    fn to_value(value: &Self::Value) -> ::greem::Value<'_> {
                        ::greem::Value::Str(::std::borrow::Cow::Borrowed(value))
                    }
                    fn from_input(value: &::greem::InputValue) -> ::core::result::Result<Self::Value, ::greem::InputError> {
                        match value {
                            ::greem::InputValue::String(s) => Ok(s.clone()),
                            other => Err(::greem::InputError::new(format!("expected a string, found {}", other.kind()))),
                        }
                    }
                }
            },
            Some(Codec::I64) => quote! {
                impl ::greem::Scalar for super::types::#tag {
                    type Value = i64;
                    fn to_value(value: &Self::Value) -> ::greem::Value<'_> {
                        ::greem::Value::Int(*value)
                    }
                    fn from_input(value: &::greem::InputValue) -> ::core::result::Result<Self::Value, ::greem::InputError> {
                        match value {
                            ::greem::InputValue::Int(i) => Ok(*i),
                            ::greem::InputValue::String(s) => s.parse().map_err(|e| ::greem::InputError::new(format!("invalid integer: {e}"))),
                            other => Err(::greem::InputError::new(format!("expected an integer, found {}", other.kind()))),
                        }
                    }
                }
            },
            None => quote!(),
        };
        let completion = Self::leaf_completion(&tag, quote!(rt::ToLeaf<super::types::#tag>));
        quote! {
            #codec
            impl rt::ToLeaf<super::types::#tag> for <super::types::#tag as ::greem::Scalar>::Value {
                fn to_leaf<'a>(self) -> ::core::result::Result<::greem::Value<'a>, ::greem::Error> where Self: 'a {
                    Ok(<super::types::#tag as ::greem::Scalar>::to_value(&self).into_owned())
                }
                fn leaf_is_null(&self) -> bool {
                    matches!(<super::types::#tag as ::greem::Scalar>::to_value(self), ::greem::Value::Null)
                }
            }
            impl rt::ToLeaf<super::types::#tag> for &<super::types::#tag as ::greem::Scalar>::Value {
                fn to_leaf<'a>(self) -> ::core::result::Result<::greem::Value<'a>, ::greem::Error> where Self: 'a {
                    Ok(<super::types::#tag as ::greem::Scalar>::to_value(self))
                }
                fn leaf_is_null(&self) -> bool {
                    matches!(<super::types::#tag as ::greem::Scalar>::to_value(*self), ::greem::Value::Null)
                }
            }
            #completion
        }
    }
}

#[cfg(test)]
mod tests {
    use super::generate;
    use std::collections::BTreeMap;

    fn generate_sdl(sdl: &str) -> Result<String, crate::Error> {
        generate(
            &[("test.graphql".to_owned(), sdl.to_owned())],
            &BTreeMap::new(),
            &[],
            false,
        )
    }

    #[test]
    fn incremental_directives_are_supplied_independently() {
        let base = "type Query { a: Int }\n";
        let defer = "directive @defer(if: Boolean! = true, label: String) on FRAGMENT_SPREAD | INLINE_FRAGMENT\n";
        let stream = "directive @stream(if: Boolean! = true, label: String, initialCount: Int = 0) on FIELD\n";
        let commented = format!(
            "{base}# directive @defer is mentioned in a comment\ndirective @deferred(x: Int) on FIELD\ndirective # comment between keyword and name\n@stream(if: Boolean! = true, label: String, initialCount: Int = 0) on FIELD\n"
        );
        for sdl in [
            base.to_owned(),
            format!("{base}{defer}"),
            format!("{base}{stream}"),
            format!("{base}{defer}{stream}"),
            commented,
        ] {
            let code = generate_sdl(&sdl).unwrap_or_else(|e| panic!("{sdl}: {e}"));
            // Count definitions, not mentions: the embedded SDL keeps its comments.
            assert_eq!(code.matches("@defer(").count(), 1, "{sdl}");
            assert_eq!(code.matches("@stream(").count(), 1, "{sdl}");
        }
    }

    #[test]
    fn colliding_legal_names_stay_distinct() {
        let code = generate_sdl(
            "type Query { s: Schema ab: A_B a: A }\ntype Schema { a: Int }\ntype A_B { c(x: Int): Int }\ntype A { B_c(x: Int): Int }",
        )
        .unwrap();
        assert!(code.contains("pub mod Schema_ {"), "{code}");
        assert!(code.contains("pub type Schema<"), "{code}");
        let flat: String = code.chars().filter(|c| !c.is_whitespace()).collect();
        assert!(
            flat.contains("typeArgs=super::__private::args::A_B::c;"),
            "{code}"
        );
        assert!(
            flat.contains("typeArgs=super::__private::args::A::B_c;"),
            "{code}"
        );
        // `Schema` and `Schema_` stay distinct; std names shadowed by fields or
        // types still resolve because generated code is fully qualified.
        let code = generate_sdl(
            "type Query { s: Schema t: Schema_ sh: Shadows }\ntype Schema { a: Int }\ntype Schema_ { a: Int }\ntype Shadows { Result(x: Int): Int Vec(x: Int): Int Option(x: Int): Int }\ntype Option { a: Int }\ntype Vec { a: Int }",
        )
        .unwrap();
        assert!(
            code.contains("pub mod Schema_ {") && code.contains("pub mod Schema__ {"),
            "{code}"
        );
        // The build version is the generator's, as a literal.
        assert!(
            code.contains(concat!("= \"", env!("CARGO_PKG_VERSION"), "\";")),
            "{code}"
        );
        assert!(!code.contains("::greem::BUILD_VERSION"), "{code}");
        // Enum values named like the helpers: the helpers are trait items, so
        // nothing generated refers to them by an inherent path.
        let code = generate_sdl(
            "type Query { h(x: Helpers): Helpers }\nenum Helpers { VALUES name from_name gen }",
        )
        .unwrap();
        assert!(code.contains("impl ::greem::Enum for Helpers"), "{code}");
        assert!(!code.contains("Self::from_name"), "{code}");
        assert!(code.contains("r#gen"), "{code}");
        // `str` as a field marker or an enum must not capture the primitive.
        let code = generate_sdl("type Query { str: String! e: str }\nenum str { a }").unwrap();
        // `for &str` is the enum itself; the primitive never appears bare.
        assert!(
            !code.contains("&'static str") && !code.contains(": &str"),
            "{code}"
        );
        assert!(code.contains("pub enum str"), "{code}");
    }

    #[test]
    fn recursive_input_objects_are_boxed() {
        // A non-null self reference is invalid GraphQL; nullable and mutual
        // recursion are the shapes that need indirection.
        let code = generate_sdl(
            "type Query { a(f: Filter): Int }\ninput Filter { not: Filter all: [Filter!] other: Other }\ninput Other { back: Filter! plain: Leaf }\ninput Leaf { v: Int }",
        )
        .unwrap();
        // prettyplease may wrap long field types; compare without whitespace.
        let flat: String = code.chars().filter(|c| !c.is_whitespace()).collect();
        assert!(
            flat.contains("pubnot:::std::option::Option<::std::boxed::Box<Filter>>"),
            "{code}"
        );
        assert!(
            flat.contains("puball:::std::option::Option<::std::vec::Vec<Filter>>"),
            "{code}"
        );
        assert!(
            flat.contains("pubother:::std::option::Option<::std::boxed::Box<Other>>"),
            "{code}"
        );
        assert!(flat.contains("pubback:::std::boxed::Box<Filter>"), "{code}");
        assert!(
            flat.contains("pubplain:::std::option::Option<Leaf>"),
            "{code}"
        );
    }
}
